config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :food_items do
    collection do
      get :search, :action => 'search_foods', :as => 'search_foods'
      get 'search/:q', :action => 'search', :as => 'search'
    end
  end
  get 'contact_us' => 'home#contact_us'
  get 'menu' => 'home#menu'

  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  validates :name, :price, presence: true
  validates :price, :numericality => { :greater_than_or_equal_to => 0 } 
  has_many :orders

  def self.search(term)
    where('name LIKE ?', "%#{term}%")
  end

  def image_url_or_default
    if imgage_url.present?
     imgage_url
    else
      "http://loremflickr.com/320/240/food"
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food_item
  validates :quantity, presence: true, numericality: true
  validates :customer_name, presence: true
  validates :customer_phone_number, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :food_items, dependent: :destroy
  def to_s
    name || "No name"
  end
end

app/models/service_fee.rb
class ServiceFee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
    @food_item = FoodItem.find(params[:id])
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @foods_search = FoodItem.all
    if params[:term]
      @foods_search = FoodItem.search(params[:term])
    end
  end

  def search_foods
    redirect_to search_food_items_path(params[:q])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section_id, :imgage_url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact_us
  end

  def menu
    @sections = Section.all
    @foods = FoodItem.all
    if params[:section_id].present?
      @current_section = Section.find(params[:section_id])
      @foods = @current_section.food_items
    end
    if params[:sort_column] 
      @foods = @foods.order("#{params[:sort_column]} #{params[:sort_direction]}")
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @item = FoodItem.find(params[:food_item_id])
    @order = @item.orders.build
  end

  def show
    @order = Order.find(params[:id])
    @food_item = FoodItem.find(@order.food_item_id)
    @order_at = @order.created_at.localtime.strftime '%a, %d %B %Y %H:%M'
  end

  def create
    @item = FoodItem.find(params[:food_item_id])
    @order = @item.orders.build order_params
    @srv_fee = ServiceFee.find_by_description("Delivery")

    @order.total = @order.quantity * @item.price + @srv_fee.cost

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Thanks for your orders!' }
        format.json { render :show, status: :created, location: @order }
      else
        render 'new'
      end
    end
  end

  def order_params
    params.require(:order).permit(:quantity, :customer_name, :customer_addr, :customer_phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="form-group">
    <%= f.label :section_id %>
    <%= f.select :section_id, Section.all.map{|ele| [ele.name, ele.id]}, {}, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :imgage_url %>
    <%= f.text_field :imgage_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Imgage url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section %></td>
        <td><%= food_item.imgage_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/search.html.erb
<h1>Search</h1>

<% if @foods_search.present? %>
  <% @foods_search.each do |food_item| %>
  	<div class="card" style="width: 20rem;">
    	<img class="card-img-top">
				<%= image_tag food_item.image_url_or_default %>
			</img>
    	<div class="card-block">
       	<h4 class="card-title"><%= food_item.name %></h4>	
				<p class="card-text"><%= food_item.description %></p>
    	</div>
			<div class="card-footer">
          <small class="text-muted"><%= number_to_currency food_item.price %> (<%= food_item.section%>)</small>
      </div>
  	</div>
    <br>
  <% end %>
<% else %>
	<p>There are no food name contains the term(s) '<%= params[:term] %>'</p>
<% end %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<% if notice %>

  <br>

  <%= link_to 'Edit', edit_food_item_path(@food_item) %> |
  <%= link_to 'Back', food_items_path %>

<% else %>
  <div class="splash-box" style="background:flex-wrapb"><%= image_tag @food_item.image_url_or_default, style: 'height:auto%;width:100%;' %>
  </div>
  <hr/>

  <h4>
    <%= @food_item.name %>
  </h4>
  <br>
  <p>
    <%= @food_item.description %>

    <br>
    <hr/>
    <strong>
    Price:
    <%= number_to_currency @food_item.price %>
    <br>
    Menu:
    <%= @food_item.section %>
    </strong>
  </p>



<% end %>
</div>

app/views/home/contact_us.html.erb
<head>
<style type="text/css">
    .contact_us_bg {
      background-repeat:no-repeat;
      background-position: center;
      background-attachment: fixed;
      background-size: cover;
    }
</style>
</head>

<h1 style="color: rgb(100, 100, 100)">Contact us</h1>
<body class="contact_us_bg" background="<%= image_url('contact_us.jpeg') %>">
  <div class="row content">
    <div class="col-sm-3">
      <div class="card card-block">
        <address>
          QResto - 48 Duong Thi Muoi Rd, Hung Ngan Garden apt, 12th Dist, Saigon
        </address>
      </div>
    </div>

    <div class="col-sm-9">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3918.3796510363413!2d106.63042910457482!3d10.858701591696759!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317529f54a2c8509%3A0x817fbd2be24c7f16!2zQ2h1bmcgY8awIEjGsG5nIE5nw6Ju!5e0!3m2!1sen!2s!4v1487436283230" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
  </div>
</body>

app/views/home/index.html.erb
<head>
<style type="text/css">
    .main_bg {
      background-repeat:no-repeat;
      background-position: center;
      background-attachment: fixed;
      background-size: cover;
    }
</style>
</head>

<h1>Q Resto</h1>
<body class="main_bg" background="<%= image_url('qresto_bg.jpeg') %>">
  <div class="container">
    <h1 class="display-4">Welcome</h1>
    <h2 class="lead">Food and Feed</h2>
  </div>
</body>

app/views/home/menu.html.erb
<head>
<style type="text/css">

.menu_bg {
  background-repeat:no-repeat;
  background-position: center;
  background-attachment: fixed;
  background-size: cover;
}

</style>
</head>


<% if notice != '' %>
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
<% end %>


<h1 style="color: orange">Menu</h1>

<div class="btn-group">
  <% @sections.each do |section| %>
    <%= link_to section.name, menu_path(section_id: section.id), class: "btn #{params[:section_id] == section.id.to_s ? 'btn-primary' : 'btn-secondary'}" %>
  <% end %>
</div>

<br>
<br>

<% if @current_section %>
  <div class="card card-block">
		<%= form_tag nil, {:method => :get} do %>
			<div class='form-inline'>
				<%= select_tag :sort_column, options_for_select(['Name', 'Price']), class: 'form-control mr-sm-2' %>
				<%= select_tag :sort_direction, options_for_select(['Asc', 'Desc']), class: 'form-control mr-sm-2' %>
				<%= submit_tag 'Sort', class: 'btn btn-secondary' %>
        <%= hidden_field_tag :section_id , @current_section.id %>
			</div>
		<% end %>
  </div>

	<br>
	<br>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Image</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= number_to_currency item.price %></td>
          <td><%= image_tag item.image_url_or_default, style: 'max-width:100px' %></td>
          <td><%= link_to "Order", new_order_path(food_item_id: item.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <body background="<%= image_url('foods.jpeg') %>" class="menu_bg">
    <div class="card-columns">
      <% @foods.each do |food_item| %>
        <div class="card card-dark">
          <!--Card image-->
          <div class="view overlay hm-white-slight">
            <img src="<%= food_item.image_url_or_default %>" class="img-fluid">
            <a>
              <div class="mask waves-effect waves-light"></div>
            </a>
          </div>


          <!--Card content-->
          <div class="card-block">
            <!--Social shares button-->
            <a class="activator"><i class="fa fa-share-alt"></i></a>
              <!--Title-->
              <h4 class="card-title"><%= food_item.name %></h4>
              <hr>
              <!--Text-->
              <a href="<%= food_item_path(id: food_item.id) %>" class="d-flex flex-row-reverse"><h5 class="waves-effect waves-light p-2">Read more <i class="fa fa-chevron-right"></i></h5></a>
          </div>
          <!--/.Card content-->

          <div class="card-footer">
            <p class="card-text"><small class="text-muted"><%= number_to_currency food_item.price %> (<%= food_item.section%>)</small></p>
          </div>
        </div>
        <!--/.Card Dark-->
      <% end %>
    </div>
    <br>
  </body>
<% end %>

app/views/layouts/_navbar.html.erb
<head>
  <style type="text/css">
    .navbar {
      margin-bottom: 20px;
      border-radius: 0;
    }
  </style>
</head>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">QResto</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= menu_path %>">Menu<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="<%= contact_us_path %>">Contact us<span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <a class="form-inline my-2 my-lg-0">
        <%= form_tag(search_food_items_path(:term), :method => "get", id: "search-form", html: {class: 'form-group'}) do %>
      	<%= text_field_tag :term, params[:term], class: 'form-control mr-sm-2', placeholder: "Food names" %>
      	<%= submit_tag "Search", class: 'btn btn btn-outline-success my-2 my-sm-0', :name => nil %>
      	<% end %>
      </a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qresto</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/orders/new.html.erb
<h1>Order for <%= @item.name %></h1>

<%= form_for @order, url: orders_path(food_item_id: @item.id) do |f| %>
  <% if @order.errors.present? %>
    <div class="alert alert-dangerr">
      <%= @order.errors.full_messages.to_sentence %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :quantity %>
    <%= f.number_field :quantity, class: "form-control" %>
    <%= f.label :customer_name %>
    <%= f.text_field :customer_name, class: "form-control" %>
    <%= f.label :customer_address %>
    <%= f.text_field :customer_addr, class: "form-control" %>
    <%= f.label :phone_number %>
    <%= f.text_field :customer_phone_number, class: "form-control" %>
  </div>
  <%= f.submit nil, class: "btn btn-primaryy" %>
<% end %>

app/views/orders/show.html.erb
<head>
<style>
  table {
    border-collapse: collapse;
    width: 100%;
  }

  th, td {
    text-align: left;
    padding: 8px;
    border-bottom: 1px solid #ddd;
  }


  th {
    background-color: #4CAF50;
    color: white;
  }

</style>
</head>

<body>
<div class="container">

<% if notice != '' %>
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
<% end %>

<h2 style="color: rgb(0, 127, 255)">Order details</h2>

<table>
  <tr>
    <th>No</th>
    <th>Items</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
  <tr>
    <td>1</td>
    <td><%= @food_item.name %></td>
    <td><%= @order.quantity %></td>
    <td><%= @food_item.price %> </td>
  </tr>
  <tr>
    <td>2</td>
    <td>Delivery service</td>
    <td>1</td>
    <td>20000</td>
  </tr>
  <tr>
    <td></td>
    <td><strong>Total</strong></td>
    <td></td>
    <td><strong><%= @order.total %></strong></td>
  </tr>
</table>

<br>
<h5> <strong style="color: #800080">Name:</strong> <%= @order.customer_name %></h5>
<h5> <strong style="color: #800080">Phone:</strong> <%= @order.customer_phone_number %> </h5>
<h5> <strong style="color: #800080">Address:</strong> <%= @order.customer_addr %> </h5>
<h5> <strong style="color: #800080">Order at:</strong>
  <% if @order_at %>
    <%= @order_at %>
  <% else %>
    <%= @order.created_at %>
  <% end %>
</h5>
</div>
</body>